services:
  - type: web
    runtime: node
    name: tujitegemee-api
    buildCommand: npm install && npm run build
    startCommand: NODE_OPTIONS='--experimental-specifier-resolution=node' npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health